repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        types: [file]
      - id: end-of-file-fixer
        types: [file]
      - id: trailing-whitespace
        types: [file]
      - id: check-json
        types: [file]
      - id: name-tests-test
      #   types: [file]
      # - id: requirements-txt-fixer
        types: [file]
      - id: name-tests-test
        types: [file]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--line-length=120]
        types: [file]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [file]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        types: [file]
        args: [--max-line-length=120]
